version: "3.9"
services:
  php:
    restart: always
    build:
      context: .
      dockerfile: build/php/Dockerfile
    networks:
      intern:
        ipv4_address: 10.0.2.3
    volumes:
      - ./logs:/usr/src/backend/logs
      - ./ch/brueggli/backend/src/.:/usr/src/backend
      - /usr/src/backend/vendor
  nginx:
    restart: always
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      intern:
        ipv4_address: 10.0.2.2
    volumes:
      - ./config/nginx:/etc/nginx
      - ./ch/brueggli/ui/app/.:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules
      - /usr/share/nginx/html/.angular
  mysql:
    restart: always
    image: "mariadb:10.11-jammy"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PW}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PW}"
    networks:
      intern:
        ipv4_address: 10.0.2.4
    volumes:
      - ./config/mariadb/script:/docker-entrypoint-initdb.d
      - ./config/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql

networks:
  intern:
    name: "Internal network"
    external: false
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"